### PR TITLE
Fix initializing with Size(0, 0). closes #350, closes #348, closes #347

### LINKED ISSUE #341: App not rendering in real device on release mode or profile mode only debug mode working
I have tried to solve this issue by changing emulators, Different plugin version, different flutter sdk version, following docs carefully but nothing helped.

### LINKED ISSUE #347: how to trigger when orientation changed?
after changing the orientation, the sw and sh values are changing according to new height and widht. it s ok
But it doesnt rebuild the UI even i automatically or manually set state.
how can i solve this?

### LINKED ISSUE #348: issue on release mode
when the app  is closed and reopened the App not rendering

### LINKED ISSUE #350: All text in the app is invisible
# Description

All of the text in the app is invisible, this seems to be a reoccurring problem with this package and is preventing us from releasing the app.

# Where it occurs

We have noticed that this bug occurs on Android, specifically on release mode. I am unable to reproduce this bug on my iOS simulator or my Android simulator.

# What I have done to mitigate this

- I have added a builder method to my material app where I use `setContext()`. 
- Wrapped the `ScreenUtilInit` widget with a `MediaQuery` and passed it `data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window)` 
- Removed const from the `home` parameter of the MaterialApp.

# Extra Info + Image

- I am using GetMaterialApp instead of the vanilla MaterialApp.
- Seems to be the same issue as #348 #80 #341 #337 
- I am using the latest flutter version, flutter doctor shows no issues.
-

### PR DESCRIPTION
**Pull request by Mounir-Bouaiche**
@lizhuoyuan , Only in Production Mode, Flutter starts quicker and the native platform reports the actual resolution in a certain delai. This update only wait for the real resolution. Hope this closes #350 , closes #348 , closes #347 , closes #341

### CODE REVIEW

**Comment by BrunoJurkovic** [comment]
If this is a superior method of initialization, why only use it in release mode?

**Comment by Mounir-Bouaiche** [comment]
@BrunoJurkovic @lizhuoyuan Checkout the new optimized solution

**Comment by lizhuoyuan** [comment]
Thanks, I will find time to debug and merge them

**Comment by Mounir-Bouaiche** [comment]
Hello friend, are you planning to publish updates in pub.dev next days ?

**Comment by lizhuoyuan** [comment]
Thank you very much for your contribution, and I have noticed that you often answer questions, thank you very much.
I can't respond to other people in a timely manner, you are important.  
ty!

**Comment by Mounir-Bouaiche** [comment]
@lizhuoyuan Don't mention that please, we are dev family after all.
But I must say that last two commits are terrible and very bad, they can reproduce this last bug (initializing with zeros).
There will be a fix by the end of next week of the last error (getting informations from buildcontext after a defunct which produces null cast error).

**Pull request merged**
