### PR TITLE
support for disabling scaling

### PR DESCRIPTION
**Pull request by joker-fu**
#534 #459

### CODE REVIEW

**Comment by FullstackWEB-developer** [comment]
Thanks for your PR
I think there is a need to add a description of this feature to README.

**Comment by amrgetment** [comment]
It is useful but I think we could use a parameter in the ScreenUtilInit widget too

**Comment by joker-fu** [comment]
> It is useful but I think we could use a parameter in the ScreenUtilInit widget too

good idea

**Comment by joker-fu** [comment]
> Thanks for your PR I think there is a need to add a description of this feature to README.

added

**Comment by amrgetment** [comment]
@Mounir-Bouaiche This PR is useful, could you look into it, Thanks in advanced

**Comment by Mounir-Bouaiche** [comment]
@joker-fu Thanks for your efforts mate.
@joker-fu @FullstackWEB-developer @amrgetment Could you also check this announcment #568 . I really appreciate your advises and feedback there, thanks

**Pull request merged**
